using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace eSchool
{
    public class AutoGenFsEventArgs : System.EventArgs
    {
        // add local member variable to hold the list
        private List<int> fmStore;
        private int tmStore;
        private int yrStore;
        private bool autoGenerated =false;
        private decimal totalFee;
        //class ctor
        public AutoGenFsEventArgs(bool autoGenerated, decimal totalFee,List<int> fmStore, int tmStore, int yrStore)
        {
            this.autoGenerated = autoGenerated;
            this.totalFee = totalFee;
            this.fmStore = fmStore;
            this.tmStore = tmStore;
            this.yrStore = yrStore;
        }

        //properties
        public List<int> pfmStore
        {
            get
            {
                return fmStore;
            }
        }

        public int ptmStore
        {
            get
            {
                return tmStore;
            }
        }

        public int pyrStore
        {
            get
            {
                return yrStore;
            }
        }
        public bool pautoGenerated
        {
            get
            {
                return autoGenerated;
            }
        }
        public decimal pTotalFee
        {
            get
            {
                return totalFee;
            }
        }
    }
}
