//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Expenses = new HashSet<Expense>();
            this.Fees = new HashSet<Fee>();
            this.Incomes = new HashSet<Income>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string AccName { get; set; }
        public string AccNo { get; set; }
        public string Bank { get; set; }
        public decimal Amount { get; set; }
    
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual ICollection<Income> Incomes { get; set; }
    }
}
