//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int FeesId { get; set; }
        public string Name { get; set; }
        public int Admin_No { get; set; }
        public int Form { get; set; }
        public string Class { get; set; }
        public System.DateTime Date { get; set; }
        public int Term { get; set; }
        public int Year { get; set; }
        public decimal Amount_Paid { get; set; }
        public string ModeOfPayment { get; set; }
    
        public virtual Student_Basic Student_Basic { get; set; }
        public virtual SchoolPeriodTerm SchoolPeriodTerm { get; set; }
        public virtual SchoolPeriodYear SchoolPeriodYear { get; set; }
    }
}
