using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using eSchool.FeeUIs;

namespace eSchool
{
    public partial class FeesUI : UserControl
    {
        public static List<int> filterListOfForms;
        public static int selTerm;
        public static int selYear;

        public static bool autoGen = false;
        public static decimal autoTotalFee;
        public static List<int> autoFilterListOfForms;
        public static int autoSelTerm;
        public static int autoSelYear;

        private static FeesUI _instance;
        public static FeesUI Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new FeesUI();
                }
                return _instance;
            }
        }
        public FeesUI()
        {
            InitializeComponent();
        }

        private void SetToolTip(Control ctl, string message)
        {
            ToolTip toolTip1 = new ToolTip();
            toolTip1.UseFading = true;
            toolTip1.UseAnimation = true;
            //toolTip1.IsBalloon = true;
            toolTip1.AutoPopDelay = 5000;
            toolTip1.InitialDelay = 1000;
            toolTip1.ReshowDelay = 500;
            toolTip1.ShowAlways = true;
            toolTip1.SetToolTip(ctl, message);
        }
        private void TermImageSet()
        {
            if (Properties.Settings.Default.CurrentTerm ==1)
            {
                //this.pBoxLogoTerm.Image = FeeUILogo.logo_term1;
                lblTerm.Text = "Term: 1";
            }
            if (Properties.Settings.Default.CurrentTerm ==2)
            {
                //this.pBoxLogoTerm.Image = FeeUILogo.logo_term2;
                lblTerm.Text = "Term: 2";
            }
            if (Properties.Settings.Default.CurrentTerm == 3)
            {
                //this.pBoxLogoTerm.Image = FeeUILogo.logo_term3;
                lblTerm.Text = "Term: 3";
            }
        }
        private void FeesUI_Load(object sender, EventArgs e)
        {
            //UI code
            TermImageSet();
            SetToolTip(bunifuCircleProgressbarRegistered,"% Students With Fee Records");
            SetToolTip(bunifuCircleProgressbarCleared,"% Students With Completed Payment");
            SetToolTip(lblPaid,"Total Paid this Term"); SetToolTip(bunifuCustomLabel8, "Total Paid this Term");
            SetToolTip(lblRequred,"Total Required this Term"); SetToolTip(bunifuCustomLabel9, "Total Required this Term");

            lblDateNow.Text = DateTime.Now.ToString("dd MMM yyy");
            lblDateDay.Text = DateTime.Now.DayOfWeek.ToString();
            FeeUI_Show fuui = FeeUI_Show.Instance;
            fuui.btnSaveStructure.Visible = false;
            //tab1 selected =true;

            //Show FeePayment
            tab1_Click(sender, e);


            #region PassMoreDataDelegate Subscription
            ///this is data loaded at save with new fee structure
            // initialize the data by subscribing our method
            FrmCreateFStruct.ListUpdated += new FrmCreateFStruct.PassMoreDataDelegate(GridDataList);

            #endregion

            #region PassMoreDataDelegate Subscription under Auto
            ///this is data loaded at save with new fee structure
            // initialize the data by subscribing our method
            StructureListItem.AutoListUpdated += StructureListItem_AutoListUpdated;

            #endregion

            //referesh the progress bars
            //TODO lazy loading
            FeePayment fp = FeePayment.Instance;
            //fp.Copy_FeePayment_Load();
        }

        private void StructureListItem_AutoListUpdated(object sender, AutoGenFsEventArgs e)
        {
            autoGen = e.pautoGenerated;
            autoTotalFee = e.pTotalFee;
            autoFilterListOfForms = e.pfmStore;
            autoSelTerm = e.ptmStore;
            autoSelYear = e.pyrStore;
        }

        private void TabSwitcher(Control UIinstance)
        {
            if (!FeesUI.Instance.container.Controls.Contains(UIinstance))
            {
                FeesUI.Instance.container.Controls.Add(UIinstance);
                UIinstance.Dock = DockStyle.Fill;
                UIinstance.BringToFront();
            }
            else
            {
                UIinstance.BringToFront();
            }
        }

        /// <summary>
        /// This method is called each time a fee structure is created returning a list of school forms
        /// </summary>
        /// <param name="sender", "e"></param>
        public void GridDataList(object sender, PassDataEventArgs e)
        {
            filterListOfForms = e.pfmStore;
            selTerm = e.ptmStore;
            selYear = e.pyrStore;
        }

        private void tab1_Click(object sender, EventArgs e)
        {
            //UI code
            bunifuSeparator1.Width = tab1.Width;
            bunifuSeparator1.Left = tab1.Left;

            //Show FeePayment
            TabSwitcher(FeePayment.Instance);
        }

        public void tab2_Click(object sender, EventArgs e)
        {
            //UI code
            bunifuSeparator1.Width = tab2.Width;
            bunifuSeparator1.Left = tab2.Left;

            //Show 
            TabSwitcher(FeesStructure.Instance);
        }
      
        private void tab3_Click(object sender, EventArgs e)
        {
            //UI code
            bunifuSeparator1.Width = tab3.Width;
            bunifuSeparator1.Left = tab3.Left;

            //TODO charts baby
            TabSwitcher(FeeCharts.Instance);

            FeeCharts fch = FeeCharts.Instance;
            fch.Global_FeeCharts_Load();
        }
    }
}
