//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public string InvoiceNo { get; set; }
        public string Category { get; set; }
        public string Client { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
