//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentImport
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Size { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int Status { get; set; }
        public string FileLocation { get; set; }
    }
}
