using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EschoolLibrary
{
    /// <summary>
    /// Collection properties must implement the IListSource interface to enable 
    /// two-way data binding with sorting when using Windows Forms.
    /// 
    /// This class enables two-way data binding as well as sorting. 
    /// The class derives from ObservableCollection<T> and adds an explicit implementation 
    /// of IListSource. The GetList() method of IListSource is implemented to return an 
    /// IBindingList implementation that stays in sync with the ObservableCollection. 
    /// The IBindingList implementation generated by ToBindingList supports sorting. 
    /// The ToBindingList extention method is defined in the EntityFramework assembly.
    /// 
    /// 
    /// EF 5.0 does not support the above :(
    /// </summary>
    /// 


    public class ObservableListSource<T> : ObservableCollection<T>, IListSource
            where T : class
    {
        private IBindingList _bindingList;

        bool IListSource.ContainsListCollection { get { return false; } }

        IList IListSource.GetList()
        {
            return _bindingList ?? (_bindingList = this.ToBindingList());
        }
    }
}
