//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EschoolLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverHeadCategory
    {
        public int Id { get; set; }
        public string OverHead { get; set; }
    }
}
